### ISSUE TITLE
Construct AnVIL website with links to building block applications like Gen3 and Terra

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#105]
┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/ANVIL-295)
┆Issue Type: Task
┆Sprint: Backlog
┆containerName: AnVIL
┆Issue Number: ANVIL-295

**Comment by kozbo** [comment]
Blocked: Can’t link to Gen3 until security is cleared

**Comment by kozbo** [comment]
Still waiting for sign off on the SSP
