### ISSUE TITLE
Create plan for unified branding of AnVIL portal components

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#115]
[~dave] will need your help on this

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-118)
┆Issue Type: Story
┆Project Name: AnVIL
┆Issue Number: ANVIL-118

**Comment by kozbo** [comment]
This is done. 

Color schemes have been selected and Logo has been revamped to work with the various components of AnVIL
