### ISSUE TITLE
1000G Metadata ingestion on gen3.theanvil.io

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#117]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-125)
┆Issue Type: Story
┆Sprint: CA May Sprint
┆Project Name: AnVIL
┆Issue Number: ANVIL-125

**Comment by kozbo** [comment]
➤ Garrett Rupp commented:

(Duplicative)
