### ISSUE TITLE
Consult to Terra developers on WES/DOS addition to Terra, take feedback on changes to WES/DOS to GA4GH

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#19]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-18)
┆Issue Type: Story
┆Project Name: AnVIL
┆Issue Number: ANVIL-18

**Comment by kozbo** [comment]
[~briandoconnor] Do you know what progress Terra has made on WES?
