### ISSUE TITLE
Develop Dockstore so that it can support other containerized applications

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#22]
Develop Dockstore so that it can support other containerized applications (e.g., UCSC Genome Browser) as “apps”.  These are long-lived services triggered by and for FireCloud users.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/ANVIL-3)
┆Issue Type: Epic
┆Sprint: Backlog
┆containerName: AnVIL
┆Issue Number: ANVIL-3

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

This is also being handled in STAGE-56

**Comment by kozbo** [comment]
➤ Cricket Sloan commented:

[~kosborn] I am handing this ticket to you as the Project Manager for AnVIL.  The reviewer is the point person on the Seabright Team.  

This Epic is scheduled for completion in Dockstore 1.7.  However, we are planning a kill switch as the work with Leo is mismatched in time and we will not want to launch this feature with no place to launch the apps.
