### ISSUE TITLE
GA4GH services

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#27]
Establish WES services that allow compute of Nextflow, Toil Native workflows, etc. in Firecloud. Refine full DRS (DOS) support in FireCloud

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-8)
┆Issue Type: Story
┆Project Name: AnVIL
┆Issue Number: ANVIL-8

**Comment by kozbo** [comment]
This was created based on the original grant text, but the work scope has changed significantly. pertinent work is covered in other tickets.
