### ISSUE TITLE
Dockstore-ize UCSC and register these “apps” in Dockstore

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#32]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-13)
┆Issue Type: Story
┆Project Name: AnVIL
┆Issue Number: ANVIL-13
┆Epic: Define Apps

**Comment by cricketsloan** [comment]
[~accountid:5bcf5eb2a6ec23204d6bd87a] \- Does this ticket represent UCSC GB dockerized for you?  We have it dockerized but we may have licensing issues to register it in Dockstore.  It is not Open Source available.

**Comment by kozbo** [comment]
I think that this task should be “create a docker container that can run the Genome Browser”, which is done.  I will create other stories to settle the issue of the license for GB, note that we can already run Xena from docker-compose, which would be the other “UCSC” item to “Dockstore-ize”
