### ISSUE TITLE
Work with the Galaxy team to encapsulate Galaxy as an “app” in Dockstore

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#35]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-17)
┆Issue Type: Story
┆Project Name: AnVIL
┆Issue Number: ANVIL-17
┆Epic: Galaxy-Dockstore Integration

**Comment by kozbo** [comment]
➤ Cricket Sloan commented:

This is not the path that we are taking with Dockstore.  We are talking about Galaxy tools being in Dockstore.
