### ISSUE TITLE
When navigating to the top of a page the first RHS TOC element is not selected

### ISSUE THREAD

**Issue by kozbo** [anvilproject/AnVIL-JIRA#419]
Expecting a little ball on "Overview" on the RHS TOC.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/3f2eba26-2f53-4577-a7cb-311b8210bb68)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-446)
┆Issue Type: Story
┆containerName: AnVIL
┆Issue Number: ANVIL-446

**Comment by kozbo** [comment]
➤ Fran McDade commented:

@mim, I think another tix has resolved this #225 and #257.

**Comment by mim** [comment]
I don't think you mean me...

**Comment by kozbo** [comment]
Sorry @mim, that was for a mim from a different repo (from their first name). You got pinged when the ticket got copied over.

**Comment by kozbo** [comment]
➤ David Rogers commented:

This was fixed in #225
