### ISSUE TITLE
AnVIL F2F in Q4

### ISSUE THREAD

**Issue by cricketsloan** [anvilproject/AnVIL-JIRA#51]
Suggest that we hold our F2F adjacent to the STAGE F2F at UCSC in December

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-56)
┆Issue Type: Story
┆Sprint: CA June Sprint
┆Project Name: AnVIL
┆Issue Number: ANVIL-56

**Comment by cricketsloan** [comment]
➤ Kevin Osborn commented:

Biocunductor is in Europe on the 9-10, so do a meeting on 12-13

**Comment by kozbo** [comment]
The Broad is willing to pay for the meeting by adding $ to our award. In final review of budget with Kelly.

From Rich:

We have reviewed the request for additional funding to help cover the expenses projected for the December UCSC F2F for AnVIL.

Please see our response below.

1) Venue: $1,500 (to cover UCSC onsite location expense)

2) Transportation: $700 (shuttle from hotel to site and back, as necessary)

3) Catering: $5,000

4) Miscellaneous: $200

-------------------------------

Total: $7,400

We can allocate $7,400 of additional funding to UCSC.

Regarding the $20,000 Lodging expense...

We expect that travelling folks (including ourselves) will bill back through our respective grant travel budgets.

Please help us to secure a block of rooms at discounted rates, to help curb the expense.

Please review and advise.
