### ISSUE TITLE
Use dbGaP FHIR API to read study attributes

### ISSUE THREAD

**Issue by kozbo** [anvilproject/AnVIL-JIRA#821]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/ANVIL-848)
┆containerName: AnVIL
┆Issue Number: ANVIL-848
┆Sprint: Backlog
┆Issue Type: Story

**Comment by artinthetrees** [comment]
were you able to use the dbGaP FHIR API? I'd be really interested to know!
